### ISSUE TITLE
「Game.exe」が見つかりません

### ISSUE THREAD

**Issue by Hakuchuu** [DazedMTL/Arisa-Grimoire#1]
ダウンロードしたファイルの中に「Game.exe」が見当たりません

**Comment by dazedanon** [comment]
I do provide the Game.exe, you will need to purchase the game then apply the files.

**Comment by Hakuchuu** [comment]
I see. Thanks for the response. ReadMe only says run Game.exe, so I thought it was included.

**Comment by dazedanon** [comment]
No worries, just realized I copied the wrong ReadMe. Thanks for pointing that out.
